stages:
  load_data:
    cmd: python src\load_data.py --config=params.yaml
    deps:
    - src\get_data.py
    - src\load_data.py
    - data_given\credit.csv
    outs:
    - data\raw\credit.csv

  split_data:
    cmd: python src\split_data.py --config=params.yaml
    deps:
      - src\split_data.py
      - data\raw\credit.csv
    outs:
      - data\processed\train_credit.csv
      - data\processed\test_credit.csv